# Analysis House Data

In [1]:
# Import the required libraries
import requests
import json
import pandas as pd
import numpy as np

In [2]:
#Import house Data
#encodings = ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252', 'utf-16']

file_path = "Cleaned_Data/house_clean_final.csv"
house_df = pd.read_csv(file_path, encoding="utf-8")

house_df

,POST_CODE,MUNICIPALITY,CITY_SHIRE,SUBURB_GROUP,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,3101,Eastern municipalities and their suburbs,City of Boroondara,Mid,1500000.0,1751000.0,1950000.0,2080000.0,2207500.0,2317500.0,2380000.0,2310000.0,2.251500e+06,2775000.0,2.850000e+06
1,3102,Eastern municipalities and their suburbs,City of Boroondara,Mid,1000250.0,1235000.0,1307500.0,1632500.0,1741250.0,1878000.0,1783750.0,1835000.0,1.812500e+06,2038000.0,2.147500e+06
2,3103,Eastern municipalities and their suburbs,City of Boroondara,Mid,1585000.0,1755500.0,1997500.0,2480000.0,2390000.0,2601250.0,2556250.0,2617750.0,2.705000e+06,3000000.0,2.925750e+06
3,3104,Eastern municipalities and their suburbs,City of Boroondara,Mid,997500.0,1240000.0,1452000.0,1850000.0,1800000.0,1950000.0,1810000.0,1720000.0,1.900000e+06,2252500.0,2.230000e+06
4,3122,Eastern municipalities and their suburbs,City of Boroondara,Mid,1405000.0,1575000.0,1606500.0,1916500.0,2245000.0,2650000.0,2506500.0,2200000.0,2.512500e+06,2915000.0,2.475000e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,3338,Western municipalities and their suburbs,City of Melton,Outer,385100.0,347100.0,361700.0,363700.0,387600.0,449400.0,511700.0,492000.0,5.270000e+05,577800.0,6.210000e+05
189,3427,Western municipalities and their suburbs,City of Melton,Outer,279000.0,280000.0,325000.0,325000.0,360000.0,440500.0,500000.0,515000.0,5.600000e+05,614000.0,6.505000e+05
190,3024,Western municipalities and their suburbs,City of Wyndham,Outer,315750.0,314250.0,333000.0,355000.0,391250.0,462750.0,500000.0,496750.0,4.598333e+05,574500.0,6.198333e+05
191,3029,Western municipalities and their suburbs,City of Wyndham,Outer,354250.0,345000.0,378250.0,386375.0,427000.0,497625.0,540500.0,529125.0,5.488750e+05,583375.0,6.266250e+05
192,3030,Western municipalities and their suburbs,City of Wyndham,Outer,419500.0,438800.0,453000.0,503200.0,496200.0,594800.0,623500.0,630700.0,6.283000e+05,712300.0,7.538000e+05

In [7]:
#Import house Data
#encodings = ['utf-8', 'utf-8-sig', 'latin-1', 'cp1252', 'utf-16']

file_path = "Cleaned_Data/house_clean_final.csv"
house_df = pd.read_csv(file_path, encoding="utf-8")

house_df

,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
SUBURB_GROUP,,,,,,,,,,,
Inner,940534.31,1003813.73,1135558.82,1233495.10,1424911.76,1600823.53,1580245.10,1474318.63,1564147.06,1782034.31,1743053.92
Mid,744534.65,803727.93,892895.29,1046300.54,1155321.06,1289098.05,1248484.70,1196115.62,1286821.43,1497525.53,1485210.22
Outer,403998.82,414008.95,439214.34,478570.71,529463.36,624175.12,661519.00,636910.54,677774.26,794791.30,843619.12